"""initial schema: vocabulary and flashcard_reviews

Revision ID: 0844fa29c634
Revises: 
Create Date: 2026-08-05 01:02:31.761814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0844fa29c634'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portuguese', sa.String(length=200), nullable=False),
    sa.Column('english', sa.String(length=200), nullable=False),
    sa.Column('example_sentence', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_category'), 'vocabulary', ['category'], unique=False)
    op.create_index(op.f('ix_vocabulary_portuguese'), 'vocabulary', ['portuguese'], unique=False)
    op.create_table('flashcard_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.Enum('again', 'hard', 'medium', 'easy', name='reviewresult'), nullable=False),
    sa.Column('interval_days_before', sa.Integer(), nullable=False),
    sa.Column('interval_days_after', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flashcard_reviews')
    op.drop_index(op.f('ix_vocabulary_portuguese'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_category'), table_name='vocabulary')
    op.drop_table('vocabulary')
    # ### end Alembic commands ###
