"""add study_assistant_messages table

Revision ID: 3ce1420a7446
Revises: 5961b4e2e0b9
Create Date: 2026-09-09 01:05:01.502388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3ce1420a7446'
down_revision: Union[str, None] = '5961b4e2e0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Idempotent, matching the pattern established for the auth migration —
    # safe to retry if a later step in the same deploy attempt ever fails.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'study_assistant_messages' not in inspector.get_table_names():
        op.create_table('study_assistant_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.Enum('user', 'assistant', name='studyassistantrole'), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_study_assistant_messages_user_id'), 'study_assistant_messages', ['user_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_assistant_messages_user_id'), table_name='study_assistant_messages')
    op.drop_table('study_assistant_messages')
    # ### end Alembic commands ###
