"""add verbs table

Revision ID: 8131ba729b86
Revises: e425d22ecdcd
Create Date: 2026-08-06 23:39:16.247164

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.verb_seed_data import IRREGULAR_VERBS, REGULAR_VERBS

# revision identifiers, used by Alembic.
revision: str = '8131ba729b86'
down_revision: Union[str, None] = 'e425d22ecdcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('infinitive', sa.String(length=100), nullable=False),
    sa.Column('translation', sa.String(length=200), nullable=False),
    sa.Column('is_irregular', sa.Boolean(), nullable=False),
    sa.Column('irregular_conjugations', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verbs_infinitive'), 'verbs', ['infinitive'], unique=True)
    # ### end Alembic commands ###

    # Seed both the regular verb list (conjugations computed at request time
    # by the engine, nothing conjugation-related stored here) and the
    # irregular verbs (full stored paradigm per verb).
    verbs_table = sa.table(
        "verbs",
        sa.column("infinitive", sa.String),
        sa.column("translation", sa.String),
        sa.column("is_irregular", sa.Boolean),
        sa.column("irregular_conjugations", sa.Text),
    )

    rows = [
        {
            "infinitive": v["infinitive"],
            "translation": v["translation"],
            "is_irregular": False,
            "irregular_conjugations": None,
        }
        for v in REGULAR_VERBS
    ] + [
        {
            "infinitive": v["infinitive"],
            "translation": v["translation"],
            "is_irregular": True,
            "irregular_conjugations": json.dumps(v["conjugations"]),
        }
        for v in IRREGULAR_VERBS
    ]
    op.bulk_insert(verbs_table, rows)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verbs_infinitive'), table_name='verbs')
    op.drop_table('verbs')
    # ### end Alembic commands ###
