"""add grammar_topics table

Revision ID: e425d22ecdcd
Revises: 0844fa29c634
Create Date: 2026-08-06 00:38:42.770318

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.grammar_seed_data import GRAMMAR_TOPICS

# revision identifiers, used by Alembic.
revision: str = 'e425d22ecdcd'
down_revision: Union[str, None] = '0844fa29c634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_topics_category'), 'grammar_topics', ['category'], unique=False)
    op.create_index(op.f('ix_grammar_topics_slug'), 'grammar_topics', ['slug'], unique=True)
    # ### end Alembic commands ###

    # Seed the reference articles that ship with the app. This is data, not
    # schema, but keeping it in the same migration means `alembic upgrade
    # head` on a fresh clone leaves you with a fully populated Grammar
    # Reference — no separate seed script to remember to run.
    grammar_topics_table = sa.table(
        "grammar_topics",
        sa.column("slug", sa.String),
        sa.column("title", sa.String),
        sa.column("category", sa.String),
        sa.column("summary", sa.String),
        sa.column("content", sa.Text),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    now = datetime.now(timezone.utc)
    op.bulk_insert(
        grammar_topics_table,
        [
            {**topic, "created_at": now, "updated_at": now}
            for topic in GRAMMAR_TOPICS
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grammar_topics_slug'), table_name='grammar_topics')
    op.drop_index(op.f('ix_grammar_topics_category'), table_name='grammar_topics')
    op.drop_table('grammar_topics')
    # ### end Alembic commands ###
