"""add writing_submissions table

Revision ID: f4464d2a549a
Revises: 8131ba729b86
Create Date: 2026-08-25 23:58:19.063726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4464d2a549a'
down_revision: Union[str, None] = '8131ba729b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writing_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('overall_feedback', sa.Text(), nullable=False),
    sa.Column('corrections', sa.Text(), nullable=True),
    sa.Column('vocabulary_suggestions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writing_submissions')
    # ### end Alembic commands ###
