"""
Seed data for the `verbs` table.

REGULAR_VERBS only needs infinitive + translation — their conjugations are
computed on the fly by conjugation_engine.conjugate_regular() and never
stored. IRREGULAR_VERBS need every form spelled out by hand, since by
definition they don't follow the engine's rules.

Tense keys match app.services.conjugation_engine.Tense values exactly:
present, preterito_perfeito, preterito_imperfeito, future, conditional,
subjunctive_present. Each value is [eu, ele/ela/você, nós, eles/elas/vocês].
"""

REGULAR_VERBS = [
    # -ar verbs
    {"infinitive": "falar", "translation": "to speak"},
    {"infinitive": "morar", "translation": "to live, reside"},
    {"infinitive": "trabalhar", "translation": "to work"},
    {"infinitive": "estudar", "translation": "to study"},
    {"infinitive": "gostar", "translation": "to like"},
    {"infinitive": "precisar", "translation": "to need"},
    {"infinitive": "chegar", "translation": "to arrive"},
    {"infinitive": "passar", "translation": "to pass, spend time"},
    {"infinitive": "achar", "translation": "to find, think"},
    {"infinitive": "deixar", "translation": "to leave, let"},
    {"infinitive": "ficar", "translation": "to stay, become"},
    {"infinitive": "jogar", "translation": "to play (a game/sport)"},
    {"infinitive": "ajudar", "translation": "to help"},
    {"infinitive": "amar", "translation": "to love"},
    {"infinitive": "andar", "translation": "to walk"},
    {"infinitive": "cantar", "translation": "to sing"},
    {"infinitive": "cozinhar", "translation": "to cook"},
    {"infinitive": "dançar", "translation": "to dance"},
    {"infinitive": "entrar", "translation": "to enter"},
    {"infinitive": "esperar", "translation": "to wait, hope"},
    {"infinitive": "ganhar", "translation": "to win, earn"},
    {"infinitive": "lavar", "translation": "to wash"},
    {"infinitive": "limpar", "translation": "to clean"},
    {"infinitive": "mandar", "translation": "to send"},
    {"infinitive": "mudar", "translation": "to change, move"},
    {"infinitive": "pagar", "translation": "to pay"},
    {"infinitive": "parar", "translation": "to stop"},
    {"infinitive": "pensar", "translation": "to think"},
    {"infinitive": "perguntar", "translation": "to ask"},
    {"infinitive": "praticar", "translation": "to practice"},
    {"infinitive": "procurar", "translation": "to look for"},
    {"infinitive": "tocar", "translation": "to touch, play (instrument)"},
    {"infinitive": "tomar", "translation": "to take, drink"},
    {"infinitive": "usar", "translation": "to use"},
    {"infinitive": "viajar", "translation": "to travel"},
    {"infinitive": "visitar", "translation": "to visit"},
    {"infinitive": "começar", "translation": "to begin"},
    {"infinitive": "chamar", "translation": "to call"},
    {"infinitive": "explicar", "translation": "to explain"},
    {"infinitive": "fechar", "translation": "to close"},
    # -er verbs
    {"infinitive": "comer", "translation": "to eat"},
    {"infinitive": "beber", "translation": "to drink"},
    {"infinitive": "correr", "translation": "to run"},
    {"infinitive": "aprender", "translation": "to learn"},
    {"infinitive": "entender", "translation": "to understand"},
    {"infinitive": "viver", "translation": "to live"},
    {"infinitive": "escrever", "translation": "to write"},
    {"infinitive": "receber", "translation": "to receive"},
    {"infinitive": "vender", "translation": "to sell"},
    {"infinitive": "responder", "translation": "to answer"},
    {"infinitive": "depender", "translation": "to depend"},
    {"infinitive": "esconder", "translation": "to hide"},
    {"infinitive": "prometer", "translation": "to promise"},
    {"infinitive": "escolher", "translation": "to choose"},
    {"infinitive": "bater", "translation": "to hit, knock"},
    {"infinitive": "morder", "translation": "to bite"},
    {"infinitive": "varrer", "translation": "to sweep"},
    {"infinitive": "sofrer", "translation": "to suffer"},
    # -ir verbs
    {"infinitive": "partir", "translation": "to leave, depart"},
    {"infinitive": "abrir", "translation": "to open"},
    {"infinitive": "decidir", "translation": "to decide"},
    {"infinitive": "existir", "translation": "to exist"},
    {"infinitive": "permitir", "translation": "to permit, allow"},
    {"infinitive": "assistir", "translation": "to watch, attend"},
    {"infinitive": "discutir", "translation": "to discuss"},
    {"infinitive": "insistir", "translation": "to insist"},
    {"infinitive": "resistir", "translation": "to resist"},
    {"infinitive": "admitir", "translation": "to admit"},
    {"infinitive": "dividir", "translation": "to divide"},
    {"infinitive": "unir", "translation": "to unite"},
    {"infinitive": "imprimir", "translation": "to print"},
    {"infinitive": "cumprir", "translation": "to fulfill"},
    {"infinitive": "consumir", "translation": "to consume"},
]

IRREGULAR_VERBS = [
    {
        "infinitive": "ser",
        "translation": "to be (permanent/identity)",
        "conjugations": {
            "present": ["sou", "é", "somos", "são"],
            "preterito_perfeito": ["fui", "foi", "fomos", "foram"],
            "preterito_imperfeito": ["era", "era", "éramos", "eram"],
            "future": ["serei", "será", "seremos", "serão"],
            "conditional": ["seria", "seria", "seríamos", "seriam"],
            "subjunctive_present": ["seja", "seja", "sejamos", "sejam"],
        },
    },
    {
        "infinitive": "estar",
        "translation": "to be (temporary/state)",
        "conjugations": {
            "present": ["estou", "está", "estamos", "estão"],
            "preterito_perfeito": ["estive", "esteve", "estivemos", "estiveram"],
            "preterito_imperfeito": ["estava", "estava", "estávamos", "estavam"],
            "future": ["estarei", "estará", "estaremos", "estarão"],
            "conditional": ["estaria", "estaria", "estaríamos", "estariam"],
            "subjunctive_present": ["esteja", "esteja", "estejamos", "estejam"],
        },
    },
    {
        "infinitive": "ter",
        "translation": "to have",
        "conjugations": {
            "present": ["tenho", "tem", "temos", "têm"],
            "preterito_perfeito": ["tive", "teve", "tivemos", "tiveram"],
            "preterito_imperfeito": ["tinha", "tinha", "tínhamos", "tinham"],
            "future": ["terei", "terá", "teremos", "terão"],
            "conditional": ["teria", "teria", "teríamos", "teriam"],
            "subjunctive_present": ["tenha", "tenha", "tenhamos", "tenham"],
        },
    },
    {
        "infinitive": "ir",
        "translation": "to go",
        "conjugations": {
            "present": ["vou", "vai", "vamos", "vão"],
            "preterito_perfeito": ["fui", "foi", "fomos", "foram"],
            "preterito_imperfeito": ["ia", "ia", "íamos", "iam"],
            "future": ["irei", "irá", "iremos", "irão"],
            "conditional": ["iria", "iria", "iríamos", "iriam"],
            "subjunctive_present": ["vá", "vá", "vamos", "vão"],
        },
    },
    {
        "infinitive": "fazer",
        "translation": "to do, make",
        "conjugations": {
            "present": ["faço", "faz", "fazemos", "fazem"],
            "preterito_perfeito": ["fiz", "fez", "fizemos", "fizeram"],
            "preterito_imperfeito": ["fazia", "fazia", "fazíamos", "faziam"],
            "future": ["farei", "fará", "faremos", "farão"],
            "conditional": ["faria", "faria", "faríamos", "fariam"],
            "subjunctive_present": ["faça", "faça", "façamos", "façam"],
        },
    },
    {
        "infinitive": "poder",
        "translation": "to be able to, can",
        "conjugations": {
            "present": ["posso", "pode", "podemos", "podem"],
            "preterito_perfeito": ["pude", "pôde", "pudemos", "puderam"],
            "preterito_imperfeito": ["podia", "podia", "podíamos", "podiam"],
            "future": ["poderei", "poderá", "poderemos", "poderão"],
            "conditional": ["poderia", "poderia", "poderíamos", "poderiam"],
            "subjunctive_present": ["possa", "possa", "possamos", "possam"],
        },
    },
    {
        "infinitive": "querer",
        "translation": "to want",
        "conjugations": {
            "present": ["quero", "quer", "queremos", "querem"],
            "preterito_perfeito": ["quis", "quis", "quisemos", "quiseram"],
            "preterito_imperfeito": ["queria", "queria", "queríamos", "queriam"],
            "future": ["quererei", "quererá", "quereremos", "quererão"],
            "conditional": ["quereria", "quereria", "quereríamos", "quereriam"],
            "subjunctive_present": ["queira", "queira", "queiramos", "queiram"],
        },
    },
    {
        "infinitive": "dizer",
        "translation": "to say, tell",
        "conjugations": {
            "present": ["digo", "diz", "dizemos", "dizem"],
            "preterito_perfeito": ["disse", "disse", "dissemos", "disseram"],
            "preterito_imperfeito": ["dizia", "dizia", "dizíamos", "diziam"],
            "future": ["direi", "dirá", "diremos", "dirão"],
            "conditional": ["diria", "diria", "diríamos", "diriam"],
            "subjunctive_present": ["diga", "diga", "digamos", "digam"],
        },
    },
    {
        "infinitive": "vir",
        "translation": "to come",
        "conjugations": {
            "present": ["venho", "vem", "vimos", "vêm"],
            "preterito_perfeito": ["vim", "veio", "viemos", "vieram"],
            "preterito_imperfeito": ["vinha", "vinha", "vínhamos", "vinham"],
            "future": ["virei", "virá", "viremos", "virão"],
            "conditional": ["viria", "viria", "viríamos", "viriam"],
            "subjunctive_present": ["venha", "venha", "venhamos", "venham"],
        },
    },
    {
        "infinitive": "ver",
        "translation": "to see",
        "conjugations": {
            "present": ["vejo", "vê", "vemos", "veem"],
            "preterito_perfeito": ["vi", "viu", "vimos", "viram"],
            "preterito_imperfeito": ["via", "via", "víamos", "viam"],
            "future": ["verei", "verá", "veremos", "verão"],
            "conditional": ["veria", "veria", "veríamos", "veriam"],
            "subjunctive_present": ["veja", "veja", "vejamos", "vejam"],
        },
    },
    {
        "infinitive": "dar",
        "translation": "to give",
        "conjugations": {
            "present": ["dou", "dá", "damos", "dão"],
            "preterito_perfeito": ["dei", "deu", "demos", "deram"],
            "preterito_imperfeito": ["dava", "dava", "dávamos", "davam"],
            "future": ["darei", "dará", "daremos", "darão"],
            "conditional": ["daria", "daria", "daríamos", "dariam"],
            "subjunctive_present": ["dê", "dê", "demos", "deem"],
        },
    },
    {
        "infinitive": "saber",
        "translation": "to know (facts/how to)",
        "conjugations": {
            "present": ["sei", "sabe", "sabemos", "sabem"],
            "preterito_perfeito": ["soube", "soube", "soubemos", "souberam"],
            "preterito_imperfeito": ["sabia", "sabia", "sabíamos", "sabiam"],
            "future": ["saberei", "saberá", "saberemos", "saberão"],
            "conditional": ["saberia", "saberia", "saberíamos", "saberiam"],
            "subjunctive_present": ["saiba", "saiba", "saibamos", "saibam"],
        },
    },
]
